# action.yml
name: 'EdgeBit Build'
description: 'Upload build SBOM and metadata to EdgeBit'
inputs:
  edgebit-url:
    description: 'EdgeBit Organization URL, eg. https://foo.edgebit.io'
    required: true
  token:
    description: 'EdgeBit API token'
    required: true
  labels:
    description: 'Key/value labels to apply to the metadata for organizational purposes, e.g. "foo=bar, fizz=buzz"'
    required: false
  repo-token:
    description: 'GitHub API token used to post comments on pull requests'
    required: true
  sbom-file:
    description: 'Path to the SBOM file to upload'
    required: false
  image-id:
    description: 'Docker-style image ID to associate with the SBOM (eg "sha256:c2ccf1a246a929e80af584c541944452a3c7e1d013e4abac452cd571e630176a")'
    required: false
  image-tag:
    description: 'Docker-style image tag to associate with the SBOM (eg "foo/bar:latest")'
    required: false
  component:
    description: 'EdgeBit Component name to associate the SBOM with'
    required: false
  tags:
    description: 'Comma-separated list of Component tags to apply to the SBOM'
    required: false
outputs:
  message:
    description: 'Message about the SBOM uploaded to EdgeBit'
branding:
  icon: zap
  color: blue
runs:
  using: "node16"
  main: "dist/index.js"