"use strict";
// @generated by protoc-gen-connect-web v0.6.0 with parameter "target=ts,import_extension=none"
// @generated from file edgebit/platform/v1alpha/login.proto (package edgebit.platform.v1alpha, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.LoginService = void 0;
const login_pb_1 = require("./login_pb");
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from service edgebit.platform.v1alpha.LoginService
 */
exports.LoginService = {
    typeName: "edgebit.platform.v1alpha.LoginService",
    methods: {
        /**
         * @generated from rpc edgebit.platform.v1alpha.LoginService.PasswordLogin
         */
        passwordLogin: {
            name: "PasswordLogin",
            I: login_pb_1.PasswordLoginRequest,
            O: login_pb_1.PasswordLoginResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc edgebit.platform.v1alpha.LoginService.APIAccessTokenLogin
         */
        aPIAccessTokenLogin: {
            name: "APIAccessTokenLogin",
            I: login_pb_1.APIAccessTokenLoginRequest,
            O: login_pb_1.APIAccessTokenLoginResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
    }
};
