"use strict";
// @generated by protoc-gen-es v1.0.0 with parameter "target=ts,import_extension=none"
// @generated from file edgebit/platform/v1alpha/platform.proto (package edgebit.platform.v1alpha, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.UploadSBOMResponse = exports.UploadSBOMRequest = exports.UploadSBOMHeader = exports.Image = exports.AMI = exports.DockerImage = exports.GenericImage = exports.DeleteOrgAccessTokenResponse = exports.DeleteOrgAccessTokenRequest = exports.OrgAccessToken = exports.ListOrgAccessTokensResponse = exports.ListOrgAccessTokensRequest = exports.CreateOrgAccessTokenResponse = exports.CreateOrgAccessTokenRequest = exports.GetMachineInventoryResponse = exports.GetMachineInventoryRequest = exports.Workload = exports.Vulnerability = exports.VulnReference = exports.File = exports.Package = exports.Machine = exports.ListMachinesResponse = exports.ListMachinesRequest = exports.GenerateAgentDeployTokenResponse = exports.GenerateAgentDeployTokenRequest = exports.ListProjectsResponse = exports.ListProjectsRequest = exports.Project = exports.SBOMFormat = exports.VulnFixState = exports.VulnSeverity = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from enum edgebit.platform.v1alpha.VulnSeverity
 */
var VulnSeverity;
(function (VulnSeverity) {
    /**
     * @generated from enum value: VULN_SEVERITY_UNSPECIFIED = 0;
     */
    VulnSeverity[VulnSeverity["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * @generated from enum value: VULN_SEVERITY_NEGLIGIBLE = 1;
     */
    VulnSeverity[VulnSeverity["NEGLIGIBLE"] = 1] = "NEGLIGIBLE";
    /**
     * @generated from enum value: VULN_SEVERITY_LOW = 2;
     */
    VulnSeverity[VulnSeverity["LOW"] = 2] = "LOW";
    /**
     * @generated from enum value: VULN_SEVERITY_MEDIUM = 3;
     */
    VulnSeverity[VulnSeverity["MEDIUM"] = 3] = "MEDIUM";
    /**
     * @generated from enum value: VULN_SEVERITY_HIGH = 4;
     */
    VulnSeverity[VulnSeverity["HIGH"] = 4] = "HIGH";
    /**
     * @generated from enum value: VULN_SEVERITY_CRITICAL = 5;
     */
    VulnSeverity[VulnSeverity["CRITICAL"] = 5] = "CRITICAL";
})(VulnSeverity = exports.VulnSeverity || (exports.VulnSeverity = {}));
// Retrieve enum metadata with: proto3.getEnumType(VulnSeverity)
protobuf_1.proto3.util.setEnumType(VulnSeverity, "edgebit.platform.v1alpha.VulnSeverity", [
    { no: 0, name: "VULN_SEVERITY_UNSPECIFIED" },
    { no: 1, name: "VULN_SEVERITY_NEGLIGIBLE" },
    { no: 2, name: "VULN_SEVERITY_LOW" },
    { no: 3, name: "VULN_SEVERITY_MEDIUM" },
    { no: 4, name: "VULN_SEVERITY_HIGH" },
    { no: 5, name: "VULN_SEVERITY_CRITICAL" },
]);
/**
 * @generated from enum edgebit.platform.v1alpha.VulnFixState
 */
var VulnFixState;
(function (VulnFixState) {
    /**
     * @generated from enum value: VULN_FIX_STATE_UNSPECIFIED = 0;
     */
    VulnFixState[VulnFixState["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * @generated from enum value: VULN_FIX_STATE_NOTFIXED = 1;
     */
    VulnFixState[VulnFixState["NOTFIXED"] = 1] = "NOTFIXED";
    /**
     * @generated from enum value: VULN_FIX_STATE_WONTFIX = 2;
     */
    VulnFixState[VulnFixState["WONTFIX"] = 2] = "WONTFIX";
    /**
     * @generated from enum value: VULN_FIX_STATE_FIXED = 3;
     */
    VulnFixState[VulnFixState["FIXED"] = 3] = "FIXED";
})(VulnFixState = exports.VulnFixState || (exports.VulnFixState = {}));
// Retrieve enum metadata with: proto3.getEnumType(VulnFixState)
protobuf_1.proto3.util.setEnumType(VulnFixState, "edgebit.platform.v1alpha.VulnFixState", [
    { no: 0, name: "VULN_FIX_STATE_UNSPECIFIED" },
    { no: 1, name: "VULN_FIX_STATE_NOTFIXED" },
    { no: 2, name: "VULN_FIX_STATE_WONTFIX" },
    { no: 3, name: "VULN_FIX_STATE_FIXED" },
]);
/**
 * @generated from enum edgebit.platform.v1alpha.SBOMFormat
 */
var SBOMFormat;
(function (SBOMFormat) {
    /**
     * @generated from enum value: SBOM_FORMAT_UNSPECIFIED = 0;
     */
    SBOMFormat[SBOMFormat["SBOM_FORMAT_UNSPECIFIED"] = 0] = "SBOM_FORMAT_UNSPECIFIED";
    /**
     * @generated from enum value: SBOM_FORMAT_SYFT = 1;
     */
    SBOMFormat[SBOMFormat["SBOM_FORMAT_SYFT"] = 1] = "SBOM_FORMAT_SYFT";
    /**
     * @generated from enum value: SBOM_FORMAT_SPDX_JSON = 2;
     */
    SBOMFormat[SBOMFormat["SBOM_FORMAT_SPDX_JSON"] = 2] = "SBOM_FORMAT_SPDX_JSON";
    /**
     * @generated from enum value: SBOM_FORMAT_CYCLONEDX_JSON = 3;
     */
    SBOMFormat[SBOMFormat["SBOM_FORMAT_CYCLONEDX_JSON"] = 3] = "SBOM_FORMAT_CYCLONEDX_JSON";
    /**
     * @generated from enum value: SBOM_FORMAT_CYCLONEDX_XML = 4;
     */
    SBOMFormat[SBOMFormat["SBOM_FORMAT_CYCLONEDX_XML"] = 4] = "SBOM_FORMAT_CYCLONEDX_XML";
})(SBOMFormat = exports.SBOMFormat || (exports.SBOMFormat = {}));
// Retrieve enum metadata with: proto3.getEnumType(SBOMFormat)
protobuf_1.proto3.util.setEnumType(SBOMFormat, "edgebit.platform.v1alpha.SBOMFormat", [
    { no: 0, name: "SBOM_FORMAT_UNSPECIFIED" },
    { no: 1, name: "SBOM_FORMAT_SYFT" },
    { no: 2, name: "SBOM_FORMAT_SPDX_JSON" },
    { no: 3, name: "SBOM_FORMAT_CYCLONEDX_JSON" },
    { no: 4, name: "SBOM_FORMAT_CYCLONEDX_XML" },
]);
/**
 * @generated from message edgebit.platform.v1alpha.Project
 */
class Project extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string name = 2;
         */
        this.name = "";
        /**
         * @generated from field: string description = 3;
         */
        this.description = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new Project().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Project().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Project().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Project, a, b);
    }
}
exports.Project = Project;
Project.runtime = protobuf_1.proto3;
Project.typeName = "edgebit.platform.v1alpha.Project";
Project.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "created_at", kind: "message", T: protobuf_1.Timestamp },
    { no: 5, name: "updated_at", kind: "message", T: protobuf_1.Timestamp },
]);
/**
 * @generated from message edgebit.platform.v1alpha.ListProjectsRequest
 */
class ListProjectsRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListProjectsRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListProjectsRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListProjectsRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListProjectsRequest, a, b);
    }
}
exports.ListProjectsRequest = ListProjectsRequest;
ListProjectsRequest.runtime = protobuf_1.proto3;
ListProjectsRequest.typeName = "edgebit.platform.v1alpha.ListProjectsRequest";
ListProjectsRequest.fields = protobuf_1.proto3.util.newFieldList(() => []);
/**
 * @generated from message edgebit.platform.v1alpha.ListProjectsResponse
 */
class ListProjectsResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated edgebit.platform.v1alpha.Project projects = 1;
         */
        this.projects = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListProjectsResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListProjectsResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListProjectsResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListProjectsResponse, a, b);
    }
}
exports.ListProjectsResponse = ListProjectsResponse;
ListProjectsResponse.runtime = protobuf_1.proto3;
ListProjectsResponse.typeName = "edgebit.platform.v1alpha.ListProjectsResponse";
ListProjectsResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "projects", kind: "message", T: Project, repeated: true },
]);
/**
 * @generated from message edgebit.platform.v1alpha.GenerateAgentDeployTokenRequest
 */
class GenerateAgentDeployTokenRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string project_id = 1;
         */
        this.projectId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new GenerateAgentDeployTokenRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GenerateAgentDeployTokenRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GenerateAgentDeployTokenRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GenerateAgentDeployTokenRequest, a, b);
    }
}
exports.GenerateAgentDeployTokenRequest = GenerateAgentDeployTokenRequest;
GenerateAgentDeployTokenRequest.runtime = protobuf_1.proto3;
GenerateAgentDeployTokenRequest.typeName = "edgebit.platform.v1alpha.GenerateAgentDeployTokenRequest";
GenerateAgentDeployTokenRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.GenerateAgentDeployTokenResponse
 */
class GenerateAgentDeployTokenResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string deploy_token = 1;
         */
        this.deployToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new GenerateAgentDeployTokenResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GenerateAgentDeployTokenResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GenerateAgentDeployTokenResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GenerateAgentDeployTokenResponse, a, b);
    }
}
exports.GenerateAgentDeployTokenResponse = GenerateAgentDeployTokenResponse;
GenerateAgentDeployTokenResponse.runtime = protobuf_1.proto3;
GenerateAgentDeployTokenResponse.typeName = "edgebit.platform.v1alpha.GenerateAgentDeployTokenResponse";
GenerateAgentDeployTokenResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "deploy_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.ListMachinesRequest
 */
class ListMachinesRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string project_id = 1;
         */
        this.projectId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListMachinesRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListMachinesRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListMachinesRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListMachinesRequest, a, b);
    }
}
exports.ListMachinesRequest = ListMachinesRequest;
ListMachinesRequest.runtime = protobuf_1.proto3;
ListMachinesRequest.typeName = "edgebit.platform.v1alpha.ListMachinesRequest";
ListMachinesRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.ListMachinesResponse
 */
class ListMachinesResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated edgebit.platform.v1alpha.Machine machines = 1;
         */
        this.machines = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListMachinesResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListMachinesResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListMachinesResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListMachinesResponse, a, b);
    }
}
exports.ListMachinesResponse = ListMachinesResponse;
ListMachinesResponse.runtime = protobuf_1.proto3;
ListMachinesResponse.typeName = "edgebit.platform.v1alpha.ListMachinesResponse";
ListMachinesResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "machines", kind: "message", T: Machine, repeated: true },
]);
/**
 * @generated from message edgebit.platform.v1alpha.Machine
 */
class Machine extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string project_id = 2;
         */
        this.projectId = "";
        /**
         * @generated from field: string hostname = 3;
         */
        this.hostname = "";
        /**
         * @generated from field: int32 policy_violations = 4;
         */
        this.policyViolations = 0;
        /**
         * @generated from field: int32 workloads = 5;
         */
        this.workloads = 0;
        /**
         * @generated from field: int32 total_vulnerabilities = 6;
         */
        this.totalVulnerabilities = 0;
        /**
         * @generated from field: int32 actionable_vulnerabilities = 7;
         */
        this.actionableVulnerabilities = 0;
        /**
         * @generated from field: string operating_system = 8;
         */
        this.operatingSystem = "";
        /**
         * @generated from field: bool agent_alive = 10;
         */
        this.agentAlive = false;
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new Machine().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Machine().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Machine().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Machine, a, b);
    }
}
exports.Machine = Machine;
Machine.runtime = protobuf_1.proto3;
Machine.typeName = "edgebit.platform.v1alpha.Machine";
Machine.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "hostname", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "policy_violations", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "workloads", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "total_vulnerabilities", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "actionable_vulnerabilities", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "operating_system", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "last_updated", kind: "message", T: protobuf_1.Timestamp },
    { no: 10, name: "agent_alive", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.Package
 */
class Package extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string name = 2;
         */
        this.name = "";
        /**
         * @generated from field: string type = 3;
         */
        this.type = "";
        /**
         * @generated from field: bool in_use = 4;
         */
        this.inUse = false;
        /**
         * @generated from field: int32 total_vulnerabilities = 5;
         */
        this.totalVulnerabilities = 0;
        /**
         * @generated from field: int32 actionable_vulnerabilities = 6;
         */
        this.actionableVulnerabilities = 0;
        /**
         * @generated from field: string workload_id = 7;
         */
        this.workloadId = "";
        /**
         * @generated from field: string source_id = 8;
         */
        this.sourceId = "";
        /**
         * @generated from field: repeated string vulnerability_ids = 9;
         */
        this.vulnerabilityIds = [];
        /**
         * @generated from field: string version = 10;
         */
        this.version = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new Package().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Package().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Package().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Package, a, b);
    }
}
exports.Package = Package;
Package.runtime = protobuf_1.proto3;
Package.typeName = "edgebit.platform.v1alpha.Package";
Package.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "in_use", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "total_vulnerabilities", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "actionable_vulnerabilities", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "workload_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "source_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "vulnerability_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 10, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.File
 */
class File extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string filename = 2;
         */
        this.filename = "";
        /**
         * @generated from field: bool in_use = 3;
         */
        this.inUse = false;
        /**
         * @generated from field: bool executable = 4;
         */
        this.executable = false;
        /**
         * @generated from field: string package_id = 5;
         */
        this.packageId = "";
        /**
         * @generated from field: string source_id = 6;
         */
        this.sourceId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new File().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new File().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new File().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(File, a, b);
    }
}
exports.File = File;
File.runtime = protobuf_1.proto3;
File.typeName = "edgebit.platform.v1alpha.File";
File.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "in_use", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "executable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "package_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "source_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.VulnReference
 */
class VulnReference extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string url = 1;
         */
        this.url = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new VulnReference().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new VulnReference().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new VulnReference().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(VulnReference, a, b);
    }
}
exports.VulnReference = VulnReference;
VulnReference.runtime = protobuf_1.proto3;
VulnReference.typeName = "edgebit.platform.v1alpha.VulnReference";
VulnReference.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.Vulnerability
 */
class Vulnerability extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string description = 2;
         */
        this.description = "";
        /**
         * @generated from field: edgebit.platform.v1alpha.VulnSeverity severity = 3;
         */
        this.severity = VulnSeverity.UNSPECIFIED;
        /**
         * @generated from field: repeated edgebit.platform.v1alpha.VulnReference references = 4;
         */
        this.references = [];
        /**
         * @generated from field: edgebit.platform.v1alpha.VulnFixState fix_state = 5;
         */
        this.fixState = VulnFixState.UNSPECIFIED;
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new Vulnerability().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Vulnerability().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Vulnerability().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Vulnerability, a, b);
    }
}
exports.Vulnerability = Vulnerability;
Vulnerability.runtime = protobuf_1.proto3;
Vulnerability.typeName = "edgebit.platform.v1alpha.Vulnerability";
Vulnerability.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "severity", kind: "enum", T: protobuf_1.proto3.getEnumType(VulnSeverity) },
    { no: 4, name: "references", kind: "message", T: VulnReference, repeated: true },
    { no: 5, name: "fix_state", kind: "enum", T: protobuf_1.proto3.getEnumType(VulnFixState) },
]);
/**
 * @generated from message edgebit.platform.v1alpha.Workload
 */
class Workload extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string project_id = 2;
         */
        this.projectId = "";
        /**
         * @generated from field: string name = 3;
         */
        this.name = "";
        /**
         * @generated from field: string type = 4;
         */
        this.type = "";
        /**
         * @generated from field: string trust = 5;
         */
        this.trust = "";
        /**
         * @generated from field: int32 total_vulnerabilities = 6;
         */
        this.totalVulnerabilities = 0;
        /**
         * @generated from field: int32 actionable_vulnerabilities = 7;
         */
        this.actionableVulnerabilities = 0;
        /**
         * @generated from field: string source_id = 8;
         */
        this.sourceId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new Workload().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Workload().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Workload().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Workload, a, b);
    }
}
exports.Workload = Workload;
Workload.runtime = protobuf_1.proto3;
Workload.typeName = "edgebit.platform.v1alpha.Workload";
Workload.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "trust", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "total_vulnerabilities", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "actionable_vulnerabilities", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "source_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.GetMachineInventoryRequest
 */
class GetMachineInventoryRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string project_id = 1;
         */
        this.projectId = "";
        /**
         * @generated from field: string machine_id = 2;
         */
        this.machineId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new GetMachineInventoryRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GetMachineInventoryRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GetMachineInventoryRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GetMachineInventoryRequest, a, b);
    }
}
exports.GetMachineInventoryRequest = GetMachineInventoryRequest;
GetMachineInventoryRequest.runtime = protobuf_1.proto3;
GetMachineInventoryRequest.typeName = "edgebit.platform.v1alpha.GetMachineInventoryRequest";
GetMachineInventoryRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "machine_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.GetMachineInventoryResponse
 */
class GetMachineInventoryResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated edgebit.platform.v1alpha.Package packages = 2;
         */
        this.packages = [];
        /**
         * @generated from field: repeated edgebit.platform.v1alpha.File files_in_use = 3;
         */
        this.filesInUse = [];
        /**
         * @generated from field: repeated edgebit.platform.v1alpha.Workload workloads = 4;
         */
        this.workloads = [];
        /**
         * @generated from field: repeated edgebit.platform.v1alpha.Vulnerability vulnerabilities = 5;
         */
        this.vulnerabilities = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new GetMachineInventoryResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GetMachineInventoryResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GetMachineInventoryResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GetMachineInventoryResponse, a, b);
    }
}
exports.GetMachineInventoryResponse = GetMachineInventoryResponse;
GetMachineInventoryResponse.runtime = protobuf_1.proto3;
GetMachineInventoryResponse.typeName = "edgebit.platform.v1alpha.GetMachineInventoryResponse";
GetMachineInventoryResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "machine", kind: "message", T: Machine },
    { no: 2, name: "packages", kind: "message", T: Package, repeated: true },
    { no: 3, name: "files_in_use", kind: "message", T: File, repeated: true },
    { no: 4, name: "workloads", kind: "message", T: Workload, repeated: true },
    { no: 5, name: "vulnerabilities", kind: "message", T: Vulnerability, repeated: true },
]);
/**
 * @generated from message edgebit.platform.v1alpha.CreateOrgAccessTokenRequest
 */
class CreateOrgAccessTokenRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string project_id = 1;
         */
        this.projectId = "";
        /**
         * @generated from field: string description = 2;
         */
        this.description = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateOrgAccessTokenRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateOrgAccessTokenRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateOrgAccessTokenRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateOrgAccessTokenRequest, a, b);
    }
}
exports.CreateOrgAccessTokenRequest = CreateOrgAccessTokenRequest;
CreateOrgAccessTokenRequest.runtime = protobuf_1.proto3;
CreateOrgAccessTokenRequest.typeName = "edgebit.platform.v1alpha.CreateOrgAccessTokenRequest";
CreateOrgAccessTokenRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.CreateOrgAccessTokenResponse
 */
class CreateOrgAccessTokenResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string description = 2;
         */
        this.description = "";
        /**
         * @generated from field: string token = 3;
         */
        this.token = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateOrgAccessTokenResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateOrgAccessTokenResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateOrgAccessTokenResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateOrgAccessTokenResponse, a, b);
    }
}
exports.CreateOrgAccessTokenResponse = CreateOrgAccessTokenResponse;
CreateOrgAccessTokenResponse.runtime = protobuf_1.proto3;
CreateOrgAccessTokenResponse.typeName = "edgebit.platform.v1alpha.CreateOrgAccessTokenResponse";
CreateOrgAccessTokenResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.ListOrgAccessTokensRequest
 */
class ListOrgAccessTokensRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string project_id = 1;
         */
        this.projectId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListOrgAccessTokensRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListOrgAccessTokensRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListOrgAccessTokensRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListOrgAccessTokensRequest, a, b);
    }
}
exports.ListOrgAccessTokensRequest = ListOrgAccessTokensRequest;
ListOrgAccessTokensRequest.runtime = protobuf_1.proto3;
ListOrgAccessTokensRequest.typeName = "edgebit.platform.v1alpha.ListOrgAccessTokensRequest";
ListOrgAccessTokensRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.ListOrgAccessTokensResponse
 */
class ListOrgAccessTokensResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated edgebit.platform.v1alpha.OrgAccessToken tokens = 1;
         */
        this.tokens = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListOrgAccessTokensResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListOrgAccessTokensResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListOrgAccessTokensResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListOrgAccessTokensResponse, a, b);
    }
}
exports.ListOrgAccessTokensResponse = ListOrgAccessTokensResponse;
ListOrgAccessTokensResponse.runtime = protobuf_1.proto3;
ListOrgAccessTokensResponse.typeName = "edgebit.platform.v1alpha.ListOrgAccessTokensResponse";
ListOrgAccessTokensResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "tokens", kind: "message", T: OrgAccessToken, repeated: true },
]);
/**
 * @generated from message edgebit.platform.v1alpha.OrgAccessToken
 */
class OrgAccessToken extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string project_id = 2;
         */
        this.projectId = "";
        /**
         * @generated from field: string description = 3;
         */
        this.description = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new OrgAccessToken().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new OrgAccessToken().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new OrgAccessToken().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(OrgAccessToken, a, b);
    }
}
exports.OrgAccessToken = OrgAccessToken;
OrgAccessToken.runtime = protobuf_1.proto3;
OrgAccessToken.typeName = "edgebit.platform.v1alpha.OrgAccessToken";
OrgAccessToken.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "created_at", kind: "message", T: protobuf_1.Timestamp },
    { no: 5, name: "last_used", kind: "message", T: protobuf_1.Timestamp },
]);
/**
 * @generated from message edgebit.platform.v1alpha.DeleteOrgAccessTokenRequest
 */
class DeleteOrgAccessTokenRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string project_id = 1;
         */
        this.projectId = "";
        /**
         * @generated from field: string id = 2;
         */
        this.id = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new DeleteOrgAccessTokenRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DeleteOrgAccessTokenRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DeleteOrgAccessTokenRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DeleteOrgAccessTokenRequest, a, b);
    }
}
exports.DeleteOrgAccessTokenRequest = DeleteOrgAccessTokenRequest;
DeleteOrgAccessTokenRequest.runtime = protobuf_1.proto3;
DeleteOrgAccessTokenRequest.typeName = "edgebit.platform.v1alpha.DeleteOrgAccessTokenRequest";
DeleteOrgAccessTokenRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.DeleteOrgAccessTokenResponse
 */
class DeleteOrgAccessTokenResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new DeleteOrgAccessTokenResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DeleteOrgAccessTokenResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DeleteOrgAccessTokenResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DeleteOrgAccessTokenResponse, a, b);
    }
}
exports.DeleteOrgAccessTokenResponse = DeleteOrgAccessTokenResponse;
DeleteOrgAccessTokenResponse.runtime = protobuf_1.proto3;
DeleteOrgAccessTokenResponse.typeName = "edgebit.platform.v1alpha.DeleteOrgAccessTokenResponse";
DeleteOrgAccessTokenResponse.fields = protobuf_1.proto3.util.newFieldList(() => []);
/**
 * An image with no further details. This primarily happens when an SBOM tool
 * (e.g. syft) is ran on the workload (e.g. after a host boots)
 *
 * @generated from message edgebit.platform.v1alpha.GenericImage
 */
class GenericImage extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new GenericImage().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GenericImage().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GenericImage().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GenericImage, a, b);
    }
}
exports.GenericImage = GenericImage;
GenericImage.runtime = protobuf_1.proto3;
GenericImage.typeName = "edgebit.platform.v1alpha.GenericImage";
GenericImage.fields = protobuf_1.proto3.util.newFieldList(() => []);
/**
 * Docker image
 *
 * @generated from message edgebit.platform.v1alpha.DockerImage
 */
class DockerImage extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * Potentially full tag in registry/user/name:tag format.
         * The full format does not need to be used. The same defaults
         * that "docker pull" assumes will work.
         *
         * @generated from field: string tag = 1;
         */
        this.tag = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new DockerImage().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DockerImage().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DockerImage().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DockerImage, a, b);
    }
}
exports.DockerImage = DockerImage;
DockerImage.runtime = protobuf_1.proto3;
DockerImage.typeName = "edgebit.platform.v1alpha.DockerImage";
DockerImage.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "tag", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.AMI
 */
class AMI extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string name = 1;
         */
        this.name = "";
        /**
         * @generated from field: repeated string tags = 2;
         */
        this.tags = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new AMI().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AMI().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AMI().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AMI, a, b);
    }
}
exports.AMI = AMI;
AMI.runtime = protobuf_1.proto3;
AMI.typeName = "edgebit.platform.v1alpha.AMI";
AMI.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "tags", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
]);
/**
 * @generated from message edgebit.platform.v1alpha.Image
 */
class Image extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * type: Docker | OCI | AMI | ...
         *
         * @generated from oneof edgebit.platform.v1alpha.Image.kind
         */
        this.kind = { case: undefined };
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new Image().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Image().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Image().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Image, a, b);
    }
}
exports.Image = Image;
Image.runtime = protobuf_1.proto3;
Image.typeName = "edgebit.platform.v1alpha.Image";
Image.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "generic", kind: "message", T: GenericImage, oneof: "kind" },
    { no: 2, name: "docker", kind: "message", T: DockerImage, oneof: "kind" },
    { no: 3, name: "ami", kind: "message", T: AMI, oneof: "kind" },
]);
/**
 * @generated from message edgebit.platform.v1alpha.UploadSBOMHeader
 */
class UploadSBOMHeader extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string project_id = 1;
         */
        this.projectId = "";
        /**
         * @generated from field: edgebit.platform.v1alpha.SBOMFormat format = 2;
         */
        this.format = SBOMFormat.SBOM_FORMAT_UNSPECIFIED;
        /**
         * @generated from field: map<string, string> labels = 3;
         */
        this.labels = {};
        /**
         * @generated from field: string image_id = 4;
         */
        this.imageId = "";
        /**
         * @generated from field: string source_repo_url = 6;
         */
        this.sourceRepoUrl = "";
        /**
         * @generated from field: string source_commit_id = 7;
         */
        this.sourceCommitId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UploadSBOMHeader().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UploadSBOMHeader().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UploadSBOMHeader().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UploadSBOMHeader, a, b);
    }
}
exports.UploadSBOMHeader = UploadSBOMHeader;
UploadSBOMHeader.runtime = protobuf_1.proto3;
UploadSBOMHeader.typeName = "edgebit.platform.v1alpha.UploadSBOMHeader";
UploadSBOMHeader.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "format", kind: "enum", T: protobuf_1.proto3.getEnumType(SBOMFormat) },
    { no: 3, name: "labels", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "scalar", T: 9 /* ScalarType.STRING */ } },
    { no: 4, name: "image_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "image", kind: "message", T: Image },
    { no: 6, name: "source_repo_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "source_commit_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message edgebit.platform.v1alpha.UploadSBOMRequest
 */
class UploadSBOMRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from oneof edgebit.platform.v1alpha.UploadSBOMRequest.kind
         */
        this.kind = { case: undefined };
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UploadSBOMRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UploadSBOMRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UploadSBOMRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UploadSBOMRequest, a, b);
    }
}
exports.UploadSBOMRequest = UploadSBOMRequest;
UploadSBOMRequest.runtime = protobuf_1.proto3;
UploadSBOMRequest.typeName = "edgebit.platform.v1alpha.UploadSBOMRequest";
UploadSBOMRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "header", kind: "message", T: UploadSBOMHeader, oneof: "kind" },
    { no: 2, name: "data", kind: "scalar", T: 12 /* ScalarType.BYTES */, oneof: "kind" },
]);
/**
 * @generated from message edgebit.platform.v1alpha.UploadSBOMResponse
 */
class UploadSBOMResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UploadSBOMResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UploadSBOMResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UploadSBOMResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UploadSBOMResponse, a, b);
    }
}
exports.UploadSBOMResponse = UploadSBOMResponse;
UploadSBOMResponse.runtime = protobuf_1.proto3;
UploadSBOMResponse.typeName = "edgebit.platform.v1alpha.UploadSBOMResponse";
UploadSBOMResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
