"use strict";
// @generated by protoc-gen-connect-web v0.6.0 with parameter "target=ts,import_extension=none"
// @generated from file edgebit/platform/v1alpha/platform.proto (package edgebit.platform.v1alpha, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.EdgeBitPublicAPIService = void 0;
const platform_pb_1 = require("./platform_pb");
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from service edgebit.platform.v1alpha.EdgeBitPublicAPIService
 */
exports.EdgeBitPublicAPIService = {
    typeName: "edgebit.platform.v1alpha.EdgeBitPublicAPIService",
    methods: {
        /**
         * Project Management (org-scoped)
         *
         * @generated from rpc edgebit.platform.v1alpha.EdgeBitPublicAPIService.ListProjects
         */
        listProjects: {
            name: "ListProjects",
            I: platform_pb_1.ListProjectsRequest,
            O: platform_pb_1.ListProjectsResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Agent Deployment Token Management (project-scoped)
         *
         * @generated from rpc edgebit.platform.v1alpha.EdgeBitPublicAPIService.GenerateAgentDeployToken
         */
        generateAgentDeployToken: {
            name: "GenerateAgentDeployToken",
            I: platform_pb_1.GenerateAgentDeployTokenRequest,
            O: platform_pb_1.GenerateAgentDeployTokenResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Machine Management (project-scoped)
         *
         * @generated from rpc edgebit.platform.v1alpha.EdgeBitPublicAPIService.ListMachines
         */
        listMachines: {
            name: "ListMachines",
            I: platform_pb_1.ListMachinesRequest,
            O: platform_pb_1.ListMachinesResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Inventory Exploration (project-scoped)
         *
         * @generated from rpc edgebit.platform.v1alpha.EdgeBitPublicAPIService.GetMachineInventory
         */
        getMachineInventory: {
            name: "GetMachineInventory",
            I: platform_pb_1.GetMachineInventoryRequest,
            O: platform_pb_1.GetMachineInventoryResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Org (Project) Access Token Management (project-scoped)
         *
         * @generated from rpc edgebit.platform.v1alpha.EdgeBitPublicAPIService.CreateOrgAccessToken
         */
        createOrgAccessToken: {
            name: "CreateOrgAccessToken",
            I: platform_pb_1.CreateOrgAccessTokenRequest,
            O: platform_pb_1.CreateOrgAccessTokenResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc edgebit.platform.v1alpha.EdgeBitPublicAPIService.ListOrgAccessTokens
         */
        listOrgAccessTokens: {
            name: "ListOrgAccessTokens",
            I: platform_pb_1.ListOrgAccessTokensRequest,
            O: platform_pb_1.ListOrgAccessTokensResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc edgebit.platform.v1alpha.EdgeBitPublicAPIService.DeleteOrgAccessToken
         */
        deleteOrgAccessToken: {
            name: "DeleteOrgAccessToken",
            I: platform_pb_1.DeleteOrgAccessTokenRequest,
            O: platform_pb_1.DeleteOrgAccessTokenResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * SBOM Management (project-scoped)
         *
         * @generated from rpc edgebit.platform.v1alpha.EdgeBitPublicAPIService.UploadSBOM
         */
        uploadSBOM: {
            name: "UploadSBOM",
            I: platform_pb_1.UploadSBOMRequest,
            O: platform_pb_1.UploadSBOMResponse,
            kind: protobuf_1.MethodKind.ClientStreaming,
        },
    }
};
